name: "Send a message in the pull request and invitation to Discord"

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Send Message
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: "Thanks for contributing to vota.dev! <img src="https://midu.dev/images/midudev-this-is-fine.png" width="36" alt="This is fine Midudev logo"/> \n  don't forget to join our discord server: https://discord.gg/midudev 🔥"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
